import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ChatRoot } from "@/modules/chat/react/ChatRoot";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <ChatRoot>{children}</ChatRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
