import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChatRoot } from "@/modules/chat/react/ChatRoot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChatRoot>{children}</ChatRoot>
      </body>
    </html>
  );
}
